title: Ernesto Araya Valdivia
position: Postdoctoral researcher at Bavarian AI Chair for Foundations of Artificial Intelligence
affiliation: LMU Munich
affiliation_link:
email: araya@math.lmu.de
google_scholar: https://scholar.google.com/citations?hl=en&user=kXD5AegAAAAJ
cv_link:
github_link: https://github.com/ErnestoArayaV/
linkedin: https://www.linkedin.com/in/ernesto-araya-valdivia/
twitter:
avatar: ./assets/img/EAraya_web_profile.jpg
google_analytics: UA-111540567-4
favicon:
favicon_dark:
description:
canonical:
imprint:
data_protection:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
